#!/usr/bin/env python3
"""
Textual Application Generator

This script generates Textual TUI (Terminal User Interface) applications
from templates. It supports various application types including basic apps,
widget-based apps, layout examples, and interactive applications.

Features:
- Generate basic TUI applications
- Create widget-based templates
- Generate layout templates
- Create interactive application templates
- Custom template support

Usage:
    python textual-generator.py --type basic --name MyApp
    python textual-generator.py --type widget --name MyWidget --widget button
    python textual-generator.py --type layout --name MyLayout --layout grid
    python textual-generator.py --type interactive --name MyInteractive
"""

import argparse
import os
import sys
from pathlib import Path
from typing import Dict, List, Optional


# ============================================================================
# TEMPLATES
# ============================================================================

BASIC_APP_TEMPLATE = '''"""
{app_name} - A Textual Application

Generated by textual-generator.py
"""

from textual.app import App, ComposeResult
from textual.containers import Container
from textual.widgets import Header, Footer, Label


class {class_name}(App):
    """A simple Textual application."""

    CSS = """
    Screen {{
        background: $background 90%;
    }}

    Container {{
        width: 100%;
        height: 100%;
        content-align: center middle;
    }}

    Label {{
        text-align: center;
        width: 100%;
    }}
    """

    def compose(self) -> ComposeResult:
        """Create child widgets for the app."""
        yield Header()
        yield Container(
            Label("{app_title}", id="title"),
        )
        yield Footer()

    def on_mount(self) -> None:
        """Mount the application."""
        self.title = "{app_title}"
        self.sub_title = "Generated by textual-generator.py"


if __name__ == "__main__":
    app = {class_name}()
    app.run()
'''

WIDGET_TEMPLATES = {
    'button': '''    def compose(self) -> ComposeResult:
        """Create child widgets for the app."""
        yield Header()
        yield Container(
            Button("Click Me!", variant="primary", id="main-button"),
            Button("Secondary", variant="success", id="secondary-button"),
            id="button-container",
        )
        yield Footer()

    def on_button_pressed(self, event: Button.Pressed) -> None:
        """Handle button press events."""
        if event.button.id == "main-button":
            self.bell()
            self.notify("Main button clicked!", severity="information")
        elif event.button.id == "secondary-button":
            self.bell()
            self.notify("Secondary button clicked!", severity="information")
''',

    'input': '''    def compose(self) -> ComposeResult:
        """Create child widgets for the app."""
        yield Header()
        yield Container(
            Input(placeholder="Enter your name...", id="name-input"),
            Label("Press Enter after typing", id="instructions"),
            id="input-container",
        )
        yield Footer()

    def on_input_submitted(self, event: Input.Submitted) -> None:
        """Handle input submission events."""
        if event.input.id == "name-input":
            name = event.value
            self.notify(f"Hello, {name}!", severity="information")
            event.input.value = ""
''',

    'table': '''    def compose(self) -> ComposeResult:
        """Create child widgets for the app."""
        yield Header()
        yield Container(
            Table(id="data-table"),
            id="table-container",
        )
        yield Footer()

    def on_mount(self) -> None:
        """Populate table when app mounts."""
        table = self.query_one(Table)
        table.add_columns("Name", "Age", "Location")
        table.add_rows([
            ("Alice", "30", "New York"),
            ("Bob", "25", "London"),
            ("Charlie", "35", "Paris"),
        ])
''',

    'listview': '''    def compose(self) -> ComposeResult:
        """Create child widgets for the app."""
        yield Header()
        yield Container(
            ListView(
                ListItem(Label("Item 1")),
                ListItem(Label("Item 2")),
                ListItem(Label("Item 3")),
                ListItem(Label("Item 4")),
            ),
            id="list-container",
        )
        yield Footer()

    def on_list_view_selected(self, event: ListView.Selected) -> None:
        """Handle list item selection."""
        item_index = event.list_view.index
        self.notify(f"Selected item {item_index + 1}", severity="information")
''',

    'datagrid': '''    def compose(self) -> ComposeResult:
        """Create child widgets for the app."""
        yield Header()
        yield Container(
            DataTable(id="data-grid"),
            id="grid-container",
        )
        yield Footer()

    def on_mount(self) -> None:
        """Populate data grid when app mounts."""
        grid = self.query_one(DataTable)
        grid.add_columns("ID", "Name", "Status", "Priority")
        grid.add_rows([
            ("001", "Task A", "Complete", "High"),
            ("002", "Task B", "In Progress", "Medium"),
            ("003", "Task C", "Pending", "Low"),
        ])
''',
}

WIDGET_IMPORTS = {
    'button': 'from textual.widgets import Button',
    'input': 'from textual.widgets import Input',
    'table': 'from textual.widgets import Table',
    'listview': 'from textual.widgets import ListView, ListItem',
    'datagrid': 'from textual.widgets import DataTable',
}

LAYOUT_TEMPLATES = {
    'horizontal': '''
    CSS = """
    Screen {{
        background: $background 90%;
    }}

    Container {{
        height: 100%;
        width: 100%;
    }}

    .row {{
        height: 1fr;
        width: 100%;
        layout: horizontal;
    }}

    .box {{
        width: 1fr;
        height: 100%;
        border: solid $primary;
        content-align: center middle;
    }}
    """

    def compose(self) -> ComposeResult:
        """Create child widgets for the app."""
        yield Header()
        yield Container(
            Container(Label("Box 1"), classes="box"),
            Container(Label("Box 2"), classes="box"),
            Container(Label("Box 3"), classes="box"),
            classes="row",
        )
        yield Footer()
''',

    'vertical': '''
    CSS = """
    Screen {{
        background: $background 90%;
    }}

    .column {{
        height: 1fr;
        width: 100%;
        layout: vertical;
    }}

    .box {{
        width: 100%;
        height: 1fr;
        border: solid $primary;
        content-align: center middle;
    }}
    """

    def compose(self) -> ComposeResult:
        """Create child widgets for the app."""
        yield Header()
        yield Container(
            Container(Label("Box 1"), classes="box"),
            Container(Label("Box 2"), classes="box"),
            Container(Label("Box 3"), classes="box"),
            classes="column",
        )
        yield Footer()
''',

    'grid': '''
    CSS = """
    Screen {{
        background: $background 90%;
    }}

    .grid {{
        height: 100%;
        width: 100%;
        layout: grid;
        grid-gutter: 1 1;
        grid-size: 2 2;
    }}

    .box {{
        border: solid $primary;
        content-align: center middle;
    }}
    """

    def compose(self) -> ComposeResult:
        """Create child widgets for the app."""
        yield Header()
        yield Container(
            Container(Label("Box 1"), classes="box"),
            Container(Label("Box 2"), classes="box"),
            Container(Label("Box 3"), classes="box"),
            Container(Label("Box 4"), classes="box"),
            classes="grid",
        )
        yield Footer()
''',

    'sidebar': '''
    CSS = """
    Screen {{
        background: $background 90%;
    }}

    Container {{
        height: 100%;
    }}

    .sidebar {{
        width: 30%;
        height: 100%;
        border: solid $primary;
        dock: left;
    }}

    .main {{
        width: 1fr;
        height: 100%;
        border: solid $secondary;
    }}
    """

    def compose(self) -> ComposeResult:
        """Create child widgets for the app."""
        yield Header()
        yield Container(
            Container(
                Label("Navigation", id="nav-label"),
                classes="sidebar",
            ),
            Container(
                Label("Main Content Area", id="content-label"),
                classes="main",
            ),
        )
        yield Footer()
''',
}

INTERACTIVE_TEMPLATE = '''"""
{app_name} - An Interactive Textual Application

Generated by textual-generator.py
"""

from textual.app import App, ComposeResult
from textual.containers import Container, Horizontal, Vertical
from textual.widgets import (
    Header, Footer, Label, Button, Input, Switch,
    TextArea, Static, Tabs, TabPane
)
from textual.reactive import reactive
from textual.message import Message


class Counter(Static):
    """A counter widget."""
    count = reactive(0)

    def render(self) -> str:
        """Render the counter."""
        return f"Count: {self.count}"

    def increment(self) -> None:
        """Increment the counter."""
        self.count += 1

    def decrement(self) -> None:
        """Decrement the counter."""
        self.count -= 1


class {class_name}(App):
    """An interactive Textual application."""

    counter = Counter()

    CSS = """
    Screen {{
        background: $background 90%;
    }}

    Container {{
        height: 100%;
    }}

    .container {{
        margin: 1;
    }}

    #tabs {{
        height: 1fr;
    }}

    .tab-content {{
        padding: 1;
        border: solid $primary;
        height: 1fr;
    }}

    .control-row {{
        height: auto;
        margin: 1 0;
    }}

    .counter-section {{
        content-align: center middle;
        height: 30%;
    }}

    .button-row {{
        height: auto;
        gap: 1;
    }}
    """

    BINDINGS = [
        ("q", "quit", "Quit"),
        ("r", "reset_counter", "Reset Counter"),
    ]

    def compose(self) -> ComposeResult:
        """Create child widgets for the app."""
        yield Header()
        yield Container(
            Tabs(
                TabPane("Counter", id="counter-tab"),
                TabPane("Text Input", id="text-tab"),
                TabPane("Controls", id="controls-tab"),
            ),
            classes="container",
        )
        yield Footer()

    def on_mount(self) -> None:
        """Initialize the application."""
        self.title = "{app_title}"
        self.sub_title = "Interactive Textual Application"

        counter_tab = self.query_one("#counter-tab", TabPane)
        counter_tab.mount(
            Container(
                self.counter,
                classes="counter-section",
            ),
            Horizontal(
                Button("+", variant="success", id="increment"),
                Button("-", variant="error", id="decrement"),
                classes="button-row",
            ),
        )

        text_tab = self.query_one("#text-tab", TabPane)
        text_tab.mount(
            Vertical(
                Input(placeholder="Type something...", id="text-input"),
                TextArea(id="multi-line-text", height=10),
                Static("Output will appear here", id="output-display"),
                classes="tab-content",
            ),
        )

        controls_tab = self.query_one("#controls-tab", TabPane)
        controls_tab.mount(
            Vertical(
                Horizontal(
                    Label("Dark Mode:"),
                    Switch(value=True, id="dark-mode-switch"),
                    classes="control-row",
                ),
                Horizontal(
                    Label("Notifications:"),
                    Switch(value=True, id="notifications-switch"),
                    classes="control-row",
                ),
                classes="tab-content",
            ),
        )

    def on_button_pressed(self, event: Button.Pressed) -> None:
        """Handle button press events."""
        if event.button.id == "increment":
            self.counter.increment()
        elif event.button.id == "decrement":
            self.counter.decrement()

    def on_input_submitted(self, event: Input.Submitted) -> None:
        """Handle input submission."""
        if event.input.id == "text-input":
            output = self.query_one("#output-display", Static)
            output.update(f"You typed: {event.value}")
            event.input.value = ""

    def on_text_area_changed(self, event: TextArea.Changed) -> None:
        """Handle text area changes."""
        output = self.query_one("#output-display", Static)
        char_count = len(event.text_area.text)
        output.update(f"Characters: {char_count}")

    def action_reset_counter(self) -> None:
        """Reset the counter."""
        self.counter.count = 0
        self.notify("Counter reset!", severity="warning")


if __name__ == "__main__":
    app = {class_name}()
    app.run()
'''


# ============================================================================
# GENERATOR CLASS
# ============================================================================

class TextualGenerator:
    """Generator for Textual TUI applications."""

    def __init__(self):
        """Initialize the generator."""
        self.base_imports = [
            'from textual.app import App, ComposeResult',
            'from textual.containers import Container',
            'from textual.widgets import Header, Footer, Label',
        ]

    def generate_basic_app(self, name: str, output_dir: str) -> None:
        """Generate a basic Textual application."""
        class_name = self._to_class_name(name)
        app_title = self._to_title(name)

        content = BASIC_APP_TEMPLATE.format(
            app_name=name,
            class_name=class_name,
            app_title=app_title,
        )

        self._write_file(name, output_dir, content)
        print(f"✓ Generated basic app: {name}")

    def generate_widget_app(
        self,
        name: str,
        widget_type: str,
        output_dir: str
    ) -> None:
        """Generate a widget-based Textual application."""
        if widget_type not in WIDGET_TEMPLATES:
            print(f"✗ Error: Unknown widget type '{widget_type}'")
            print(f"Available widgets: {', '.join(WIDGET_TEMPLATES.keys())}")
            return

        class_name = self._to_class_name(name)
        app_title = self._to_title(name)

        imports = self.base_imports + [WIDGET_IMPORTS.get(widget_type, '')]
        imports = [imp for imp in imports if imp]

        header = '"""\n{app_name} - A Textual {widget_title} Application\n\nGenerated by textual-generator.py\n"""\n\n'
        header += '\n'.join(imports)
        header += '\n\n'

        app_class = f'''class {class_name}(App):
    """A {widget_type}-based Textual application."""

    CSS = """
    Screen {{
        background: $background 90%;
    }}

    Container {{
        width: 100%;
        height: 100%;
        align: center middle;
    }}
    """

    def compose(self) -> ComposeResult:
        """Create child widgets for the app."""
        yield Header()
        yield Container(
{indent(WIDGET_TEMPLATES[widget_type], 12)}
        yield Footer()

    def on_mount(self) -> None:
        """Mount the application."""
        self.title = "{app_title}"
        self.sub_title = "Generated by textual-generator.py"


if __name__ == "__main__":
    app = {class_name}()
    app.run()
'''

        content = header + app_class
        content = content.format(
            app_name=name,
            class_name=class_name,
            app_title=app_title,
            widget_title=widget_type.capitalize(),
        )

        self._write_file(name, output_dir, content)
        print(f"✓ Generated {widget_type} widget app: {name}")

    def generate_layout_app(self, name: str, layout_type: str, output_dir: str) -> None:
        """Generate a layout-based Textual application."""
        if layout_type not in LAYOUT_TEMPLATES:
            print(f"✗ Error: Unknown layout type '{layout_type}'")
            print(f"Available layouts: {', '.join(LAYOUT_TEMPLATES.keys())}")
            return

        class_name = self._to_class_name(name)
        app_title = self._to_title(name)

        imports = self.base_imports + ['from textual.containers import Container']

        header = '"""\n{app_name} - A Textual {layout_title} Layout Application\n\nGenerated by textual-generator.py\n"""\n\n'
        header += '\n'.join(imports)
        header += '\n\n'

        app_class = f'''class {class_name}(App):
    """A {layout_type} layout Textual application."""

{indent(LAYOUT_TEMPLATES[layout_type], 4)}

    def on_mount(self) -> None:
        """Mount the application."""
        self.title = "{app_title}"
        self.sub_title = "Generated by textual-generator.py"


if __name__ == "__main__":
    app = {class_name}()
    app.run()
'''

        content = header + app_class
        content = content.format(
            app_name=name,
            class_name=class_name,
            app_title=app_title,
            layout_title=layout_type.capitalize(),
        )

        self._write_file(name, output_dir, content)
        print(f"✓ Generated {layout_type} layout app: {name}")

    def generate_interactive_app(self, name: str, output_dir: str) -> None:
        """Generate an interactive Textual application."""
        class_name = self._to_class_name(name)
        app_title = self._to_title(name)

        imports = [
            'from textual.app import App, ComposeResult',
            'from textual.containers import Container, Horizontal, Vertical',
            'from textual.widgets import (',
            '    Header, Footer, Label, Button, Input, Switch,',
            '    TextArea, Static, Tabs, TabPane',
            ')',
            'from textual.reactive import reactive',
            'from textual.message import Message',
            '',
            '',
            'class Counter(Static):',
            '    """A counter widget."""',
            '    count = reactive(0)',
            '',
            '    def render(self) -> str:',
            '        """Render the counter."""',
            '        return f"Count: {{self.count}}"',
            '',
            '    def increment(self) -> None:',
            '        """Increment the counter."""',
            '        self.count += 1',
            '',
            '    def decrement(self) -> None:',
            '        """Decrement the counter."""',
            '        self.count -= 1',
            '',
        ]

        header = '"""\n{app_name} - An Interactive Textual Application\n\nGenerated by textual-generator.py\n"""\n\n'
        header += '\n'.join(imports)
        header += '\n\n'

        app_class = f'''class {class_name}(App):
    """An interactive Textual application."""

    counter = Counter()

    CSS = """
    Screen {{
        background: $background 90%;
    }}

    Container {{
        height: 100%;
    }}

    .container {{
        margin: 1;
    }}

    #tabs {{
        height: 1fr;
    }}

    .tab-content {{
        padding: 1;
        border: solid $primary;
        height: 1fr;
    }}

    .control-row {{
        height: auto;
        margin: 1 0;
    }}

    .counter-section {{
        content-align: center middle;
        height: 30%;
    }}

    .button-row {{
        height: auto;
        gap: 1;
    }}
    """

    BINDINGS = [
        ("q", "quit", "Quit"),
        ("r", "reset_counter", "Reset Counter"),
    ]

    def compose(self) -> ComposeResult:
        """Create child widgets for the app."""
        yield Header()
        yield Container(
            Tabs(
                TabPane("Counter", id="counter-tab"),
                TabPane("Text Input", id="text-tab"),
                TabPane("Controls", id="controls-tab"),
            ),
            classes="container",
        )
        yield Footer()

    def on_mount(self) -> None:
        """Initialize the application."""
        self.title = "{app_title}"
        self.sub_title = "Interactive Textual Application"

        counter_tab = self.query_one("#counter-tab", TabPane)
        counter_tab.mount(
            Container(
                self.counter,
                classes="counter-section",
            ),
            Horizontal(
                Button("+", variant="success", id="increment"),
                Button("-", variant="error", id="decrement"),
                classes="button-row",
            ),
        )

        text_tab = self.query_one("#text-tab", TabPane)
        text_tab.mount(
            Vertical(
                Input(placeholder="Type something...", id="text-input"),
                TextArea(id="multi-line-text", height=10),
                Static("Output will appear here", id="output-display"),
                classes="tab-content",
            ),
        )

        controls_tab = self.query_one("#controls-tab", TabPane)
        controls_tab.mount(
            Vertical(
                Horizontal(
                    Label("Dark Mode:"),
                    Switch(value=True, id="dark-mode-switch"),
                    classes="control-row",
                ),
                Horizontal(
                    Label("Notifications:"),
                    Switch(value=True, id="notifications-switch"),
                    classes="control-row",
                ),
                classes="tab-content",
            ),
        )

    def on_button_pressed(self, event: Button.Pressed) -> None:
        """Handle button press events."""
        if event.button.id == "increment":
            self.counter.increment()
        elif event.button.id == "decrement":
            self.counter.decrement()

    def on_input_submitted(self, event: Input.Submitted) -> None:
        """Handle input submission."""
        if event.input.id == "text-input":
            output = self.query_one("#output-display", Static)
            output.update(f"You typed: {{event.value}}")
            event.input.value = ""

    def on_text_area_changed(self, event: TextArea.Changed) -> None:
        """Handle text area changes."""
        output = self.query_one("#output-display", Static)
        char_count = len(event.text_area.text)
        output.update(f"Characters: {{char_count}}")

    def action_reset_counter(self) -> None:
        """Reset the counter."""
        self.counter.count = 0
        self.notify("Counter reset!", severity="warning")


if __name__ == "__main__":
    app = {class_name}()
    app.run()
'''

        content = header + app_class
        content = content.format(
            app_name=name,
            class_name=class_name,
            app_title=app_title,
        )

        self._write_file(name, output_dir, content)
        print(f"✓ Generated interactive app: {name}")

    def _to_class_name(self, name: str) -> str:
        """Convert name to Python class name."""
        parts = name.replace('-', '_').replace(' ', '_').split('_')
        return ''.join(word.capitalize() for word in parts if word)

    def _to_title(self, name: str) -> str:
        """Convert name to title case."""
        return name.replace('-', ' ').replace('_', ' ').title()

    def _write_file(self, name: str, output_dir: str, content: str) -> None:
        """Write generated content to file."""
        output_path = Path(output_dir) / f"{name}.py"
        output_path.parent.mkdir(parents=True, exist_ok=True)

        with open(output_path, 'w') as f:
            f.write(content)

        os.chmod(output_path, 0o755)
        print(f"  → Created: {output_path}")


def indent(text: str, spaces: int) -> str:
    """Indent text by specified number of spaces."""
    indent_str = ' ' * spaces
    return '\n'.join(indent_str + line if line.strip() else line for line in text.split('\n'))


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Generate Textual TUI applications from templates",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s --type basic --name MyApp
  %(prog)s --type widget --name MyWidget --widget button
  %(prog)s --type layout --name MyLayout --layout grid
  %(prog)s --type interactive --name MyInteractive
  %(prog)s --type widget --name InputApp --widget input --output ./apps
        """
    )

    parser.add_argument(
        '--type',
        required=True,
        choices=['basic', 'widget', 'layout', 'interactive'],
        help='Type of application to generate'
    )

    parser.add_argument(
        '--name',
        required=True,
        help='Name of the application (will be converted to class name)'
    )

    parser.add_argument(
        '--widget',
        choices=list(WIDGET_TEMPLATES.keys()),
        help='Widget type (required for --type widget)'
    )

    parser.add_argument(
        '--layout',
        choices=list(LAYOUT_TEMPLATES.keys()),
        help='Layout type (required for --type layout)'
    )

    parser.add_argument(
        '--output',
        default='.',
        help='Output directory (default: current directory)'
    )

    args = parser.parse_args()

    generator = TextualGenerator()

    if args.type == 'basic':
        generator.generate_basic_app(args.name, args.output)

    elif args.type == 'widget':
        if not args.widget:
            print("✗ Error: --widget is required for --type widget")
            print(f"Available widgets: {', '.join(WIDGET_TEMPLATES.keys())}")
            sys.exit(1)
        generator.generate_widget_app(args.name, args.widget, args.output)

    elif args.type == 'layout':
        if not args.layout:
            print("✗ Error: --layout is required for --type layout")
            print(f"Available layouts: {', '.join(LAYOUT_TEMPLATES.keys())}")
            sys.exit(1)
        generator.generate_layout_app(args.name, args.layout, args.output)

    elif args.type == 'interactive':
        generator.generate_interactive_app(args.name, args.output)

    print(f"\n✓ Generated {args.type} application: {args.name}.py")
    print(f"  To run: python {args.name}.py")
    print(f"  In {args.output}/")


if __name__ == '__main__':
    main()
